"""
Stage 4: Artefact generation.

Reads the manifest and all analysis outputs from Stages 1-3, then generates every
file required for a acme DB release into $RELEASES_BASE_DIR/<jira_ticket>/.

Files produced:
  prep.sql       — SET ROLE + DROP statements for changed function/type signatures
  deploy.lst     — ordered list of SQL files to deploy (duplicates commented out)
  post.sql       — audit table creation, column additions, and rebuild blocks
  delete         — list of SQL files to remove from the repo
  NOTES.txt      — human-readable release summary

After generating all files a count verification is performed: the number of active
(non-commented) lines in deploy.lst must equal the number of non-deleted,
non-duplicate files in the manifest. Any mismatch is a hard fail.

All generated SQL files carry a standard header comment block as required by the
coding standards. No f-string expressions span multiple lines — intermediate
variables are used instead.
"""

import argparse
import hashlib
import json
import os
import subprocess
import sys
from datetime import datetime, timezone

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from pipeline.config import Config, ConfigError
from pipeline.logger import configure_logging, get_logger
from pipeline.models import AuditGap, CascadeVictim, Manifest, SqlFile

log = get_logger(__name__)

# Deploy ordering constants
#
# Stage 4 should not invent a new order; it mirrors Stage 2 so generated
# deploy.lst remains aligned with the analysis report and count verification.
_CLASSIFICATION_ORDER: dict[str, int] = {
    "schema": 0,
    "type": 1,
    "function": 2,
    "config": 3,
    "serverless": 4,
}


# ---------------------------------------------------------------------------
# SQL header
# ---------------------------------------------------------------------------
#
# Generated SQL files need a consistent provenance block so release artefacts
# can be traced back to commit, Jira ticket, PR/MR, and generation time.

def sql_file_header(manifest: Manifest) -> str:
    """Return the standard SQL file header comment block.

    Every generated SQL file must begin with this block per the coding standards.
    """
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    lines = [
        "-- Generated by: acme-db-pipeline",
        f"-- Commit: {manifest.commit_hash}",
        f"-- Jira: {manifest.jira_ticket}",
        f"-- PR: {manifest.pr_number}",
        f"-- Timestamp: {ts}",
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# prep.sql
# ---------------------------------------------------------------------------
#
# prep.sql contains only dependency-checked drops from Stage 3. It is generated
# rather than hand-authored so signature changes are handled consistently.

def generate_prep_sql(manifest: Manifest, drop_order: list[dict]) -> str:
    """Generate prep.sql content.

    Contains SET ROLE followed by all DROP statements in the order computed by
    Stage 3. Each DROP carries an inline comment referencing the PR and the
    reason the drop is required (signature change details).
    """
    header = sql_file_header(manifest)
    lines = [header, "", 'SET ROLE "acme_admin";', ""]

    if not drop_order:
        lines.append("-- No DROP statements required for this release.")
        return "\n".join(lines)

    for entry in drop_order:
        schema = entry.get("schema", "")
        name = entry.get("name", "")
        reason = entry.get("reason", f"signature change — see {manifest.pr_number}")
        drop_stmt = entry.get("drop_statement", "")

        if not drop_stmt:
            # Reconstruct a safe fallback if the drop_statement field is missing.
            old_args = entry.get("old_args", "")
            drop_stmt = f"DROP FUNCTION IF EXISTS {schema}.{name}({old_args}) CASCADE;"

        comment_text = reason.replace("\n", " ").replace("\r", "")
        comment = f"-- {manifest.jira_ticket} {manifest.pr_number}: {comment_text}"
        lines.append(comment)
        lines.append(drop_stmt)
        lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# deploy.lst
# ---------------------------------------------------------------------------
#
# deploy.lst is the release script input. Active lines are executable scope;
# commented duplicate lines preserve reviewer context without increasing the
# deployment count.

def generate_deploy_lst(manifest: Manifest) -> str:
    """Generate deploy.lst content.

    Active (non-deleted) SQL files are listed in classification order: schema,
    type, function, config, serverless. Each classification group is preceded
    by a comment line. Intra-PR duplicate files are commented out inline with
    an annotation pointing to the canonical path.
    """
    active = [f for f in manifest.sql_files if not f.is_deleted]

    # Group by classification preserving sort order from Stage 2.
    groups: dict[str, list[SqlFile]] = {}
    for sql_file in active:
        groups.setdefault(sql_file.classification, []).append(sql_file)

    ordered_groups = sorted(
        groups.items(),
        key=lambda kv: _CLASSIFICATION_ORDER.get(kv[0], 99),
    )

    lines: list[str] = []
    group_header = f"# {manifest.jira_ticket} {manifest.pr_number}"

    for _classification, files in ordered_groups:
        lines.append(group_header)
        for sql_file in files:
            if sql_file.is_duplicate:
                annotation = sql_file.duplicate_annotation or "duplicate"
                dup_line = f"# {sql_file.relative_path} --> {annotation} in {manifest.pr_number}"
                lines.append(dup_line)
            else:
                lines.append(sql_file.relative_path)
        lines.append("")

    if lines and lines[-1] == "":
        lines.pop()

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# post.sql
# ---------------------------------------------------------------------------
#
# post.sql repairs audit structures after the main SQL release has run. Its
# blocks are generated from DB-assisted audit gaps so DevOps can review the
# exact audit work before approval.

def _add_columns_block(schema: str, table: str, columns: list[str]) -> str:
    """Return an ALTER TABLE ADD COLUMN block for adding columns to an audit table.

    Intended as a review aid when individual columns are being appended to an
    existing audit table. When columns is empty, returns a header-only block with
    no ADD COLUMN statements so callers can still detect the audit table reference.
    """
    audit_ref = f"audit.{schema}_{table}"
    lines = [f"-- REVIEW: add column(s) to {audit_ref}"]
    if columns:
        lines.append(f"ALTER TABLE {audit_ref}")
        add_parts = [f"  ADD COLUMN {col}" for col in columns]
        lines.append(",\n".join(add_parts) + ";")
    return "\n".join(lines)


def _audit_trigger_function(schema: str, table: str) -> str:
    """Return the audit trigger function body for a given base table.

    Follows the acme production pattern: resolves user identity via
    acme_crm_pvt.current_user_id() with fallback to acme_api_pvt
    for guest sessions, then records the operation in the audit table.
    """
    func_ref = f'"audit"."{schema}_{table}"'
    audit_ref = f'"audit"."{schema}_{table}"'
    lines = [
        f"CREATE OR REPLACE FUNCTION {func_ref}()",
        "RETURNS TRIGGER",
        "LANGUAGE plpgsql",
        "SECURITY DEFINER",
        "AS $$",
        "DECLARE",
        "    _guest_id UUID;",
        "    _user_id  UUID;",
        "BEGIN",
        '    SELECT "value" INTO _guest_id FROM "audit"."config" WHERE "key" = \'guest_uuid\';',
        '    SELECT * INTO _user_id FROM "acme_crm_pvt"."current_user_id"();',
        "    IF _user_id = _guest_id THEN",
        '        SELECT current_user_id INTO _user_id FROM "acme_api_pvt"."current_user_id"();',
        "    END IF;",
        "    IF (TG_OP = 'DELETE') THEN",
        f"        INSERT INTO {audit_ref} SELECT OLD.*, 'delete', NOW(), _user_id;",
        "    ELSIF (TG_OP = 'INSERT') THEN",
        f"        INSERT INTO {audit_ref} SELECT NEW.*, 'insert', NOW(), _user_id;",
        "    ELSIF (TG_OP = 'UPDATE') THEN",
        f"        INSERT INTO {audit_ref} SELECT NEW.*, 'update', NOW(), _user_id;",
        "    END IF;",
        "    RETURN NULL;",
        "END;",
        "$$;",
    ]
    return "\n".join(lines)


def _missing_audit_table_block(schema: str, table: str) -> str:
    """Return the SQL block that creates a missing audit table with trigger."""
    audit_ref = f'"audit"."{schema}_{table}"'
    base_ref = f'"{schema}"."{table}"'
    func_ref = f'"audit"."{schema}_{table}"'
    trigger_func = _audit_trigger_function(schema, table)
    lines = [
        f'-- Audit table for "{schema}"."{table}"',
        f"CREATE TABLE IF NOT EXISTS {audit_ref} (LIKE {base_ref});",
        f"ALTER TABLE {audit_ref}",
        '  ADD COLUMN IF NOT EXISTS "audit_event"   "audit"."event" NOT NULL,',
        '  ADD COLUMN IF NOT EXISTS "audit_stamp"   TIMESTAMP NOT NULL,',
        '  ADD COLUMN IF NOT EXISTS "audit_user_id" UUID;',
        "",
        trigger_func,
        "",
        f'DROP TRIGGER IF EXISTS "audit" ON {base_ref};',
        'CREATE TRIGGER "audit"',
        f"AFTER INSERT OR UPDATE OR DELETE ON {base_ref}",
        f"FOR EACH ROW EXECUTE PROCEDURE {func_ref}();",
    ]
    return "\n".join(lines)


def _rebuild_audit_table_block(
    schema: str,
    table: str,
    existing_audit_columns: list[str],
    columns_to_add: list[str],
    columns_dropped: list[str],
) -> str:
    """Return the full SOP audit table rebuild block for any existing audit table column change.

    Used for all missing_columns gaps — both ADD COLUMN and DROP COLUMN. Wraps DDL in
    a BEGIN/COMMIT block. The INSERT SELECT column list is built from existing_audit_columns
    (captured by Stage 3 before the release ran), with columns_dropped entries excluded
    (they won't exist in the new table) and one NULL per entry in columns_to_add.
    """
    audit_ref = f'"audit"."{schema}_{table}"'
    base_ref = f'"{schema}"."{table}"'
    old_table_name = f"{schema}_{table}_01"
    old_audit_ref = f'"audit"."{old_table_name}"'

    # Exclude dropped columns — the new audit table (via LIKE) will not have them.
    dropped_set = set(columns_dropped)
    retained_cols = [c for c in existing_audit_columns if c not in dropped_set]

    # INSERT SELECT: retained existing cols, one NULL per new column, audit metadata.
    select_parts: list[str] = []
    if retained_cols:
        select_parts.append("  " + ", ".join(retained_cols))
    for _ in columns_to_add:
        select_parts.append("  NULL")
    select_parts.append("  audit_event, audit_stamp, audit_user_id")
    insert_select = ",\n".join(select_parts)

    lines = [
        f'-- Rebuild "audit"."{schema}_{table}" after column change on "{schema}"."{table}"',
        f"DROP TABLE IF EXISTS {old_audit_ref};",
        "BEGIN;",
        f'ALTER TABLE {audit_ref} RENAME TO "{old_table_name}";',
        f"CREATE TABLE {audit_ref} (LIKE {base_ref});",
        f"ALTER TABLE {audit_ref}",
        '  ADD COLUMN "audit_event"   "audit"."event" NOT NULL,',
        '  ADD COLUMN "audit_stamp"   TIMESTAMP NOT NULL,',
        '  ADD COLUMN "audit_user_id" UUID;',
        f"INSERT INTO {audit_ref} SELECT",
        insert_select,
        f"FROM {old_audit_ref};",
        f"DROP TABLE {old_audit_ref};",
        "COMMIT;",
    ]
    return "\n".join(lines)


def generate_post_sql(
    manifest: Manifest,
    audit_gaps: list[dict],
) -> str:
    """Generate post.sql content from audit gap records.

    Produces blocks for: missing audit tables (with trigger), existing audit table
    column changes (full SOP rebuild — always), and missing triggers.
    If there are no audit gaps, post.sql is generated as an empty placeholder.
    """
    header = sql_file_header(manifest)
    lines = [header, "", 'SET ROLE "acme_admin";', ""]

    if not audit_gaps:
        lines.append("-- No audit actions required for this release.")
        return "\n".join(lines)

    for gap in audit_gaps:
        schema = gap["schema"]
        table = gap["table"]
        gap_type = gap["gap_type"]
        columns_to_add = gap.get("columns_to_add", [])
        columns_dropped = gap.get("columns_dropped", [])
        existing_audit_columns = gap.get("existing_audit_columns", [])

        if gap_type == "missing_audit_table":
            lines.append(_missing_audit_table_block(schema, table))
            lines.append("")

        elif gap_type == "missing_columns":
            lines.append(_rebuild_audit_table_block(
                schema, table, existing_audit_columns, columns_to_add, columns_dropped
            ))
            lines.append("")

        elif gap_type == "trigger_missing":
            lines.append(_audit_trigger_function(schema, table))
            lines.append("")
            func_ref = f'"audit"."{schema}_{table}"'
            base_table = f'"{schema}"."{table}"'
            lines.append(f'DROP TRIGGER IF EXISTS "audit" ON {base_table};')
            lines.append('CREATE TRIGGER "audit"')
            lines.append(f"AFTER INSERT OR UPDATE OR DELETE ON {base_table}")
            lines.append(f"FOR EACH ROW EXECUTE PROCEDURE {func_ref}();")
            lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# delete file
# ---------------------------------------------------------------------------
#
# Deleted SQL files are promoted through a separate delete artefact so git
# promotion can remove them after the cherry-pick without confusing deploy.lst.

def generate_delete_file(manifest: Manifest) -> str:
    """Generate the delete file listing all SQL files removed in this release.

    Returns an empty string when there are no deleted files — the file is still
    written by run() but will be empty. Each deleted file entry is preceded by
    a comment line: # <JIRA> <PR>.
    """
    if not manifest.deleted_files:
        return ""

    entry_comment = f"# {manifest.jira_ticket} {manifest.pr_number}"
    lines: list[str] = []
    for path in manifest.deleted_files:
        lines.append(entry_comment)
        lines.append(path)
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# NOTES.txt
# ---------------------------------------------------------------------------
#
# NOTES.txt is the human-readable release summary for operators. It collects
# provenance, file scope, warnings, cascade findings, and duplicate-function
# warnings in one place.

def generate_notes_txt(
    manifest: Manifest,
    db_report: dict,
    jira_base_url: str = "",
) -> str:
    """Generate NOTES.txt — the human-readable release summary."""
    jira_url = (
        f"{jira_base_url.rstrip('/')}/browse/{manifest.jira_ticket}"
        if jira_base_url
        else manifest.jira_ticket
    )

    serverless_files = [
        f.relative_path
        for f in manifest.sql_files
        if f.classification == "serverless" and not f.is_deleted
    ]

    cascade_victims: list[dict] = db_report.get("cascade_victims", [])
    duplicate_functions: list[dict] = db_report.get("duplicate_functions", [])
    all_warnings = manifest.warnings

    lines = [
        f"RELEASE NOTES — {manifest.jira_ticket} {manifest.pr_number}",
        "=" * 60,
        "",
        f"Jira: {jira_url}",
        f"PR: {manifest.pr_number}",
        f"Commit: {manifest.commit_hash}",
        f"Author: {manifest.author}",
        f"Timestamp: {manifest.timestamp}",
        "",
        "SQL FILES IN THIS RELEASE",
        "-" * 30,
    ]

    active_files = [f for f in manifest.sql_files if not f.is_deleted]
    for sql_file in active_files:
        dup_note = " [DUPLICATE]" if sql_file.is_duplicate else ""
        lines.append(f"  {sql_file.classification:12s}  {sql_file.relative_path}{dup_note}")

    if manifest.deleted_files:
        lines.extend(["", "DELETED FILES", "-" * 30])
        for path in manifest.deleted_files:
            lines.append(f"  {path}")

    if serverless_files:
        lines.extend(["", "SERVERLESS FILES TOUCHED", "-" * 30])
        for path in serverless_files:
            lines.append(f"  {path}")

    if cascade_victims:
        lines.extend(["", "CASCADE SIMULATION RESULTS", "-" * 30])
        for victim in cascade_victims:
            in_scope_label = "IN SCOPE" if victim.get("in_release_scope") else "OUT OF SCOPE"
            obj_name = victim.get("object_name", "unknown")
            obj_type = victim.get("object_type", "unknown")
            lines.append(f"  [{in_scope_label}] {obj_type}: {obj_name}")

    if duplicate_functions:
        lines.extend(["", "PRE-EXISTING DUPLICATE FUNCTIONS (WARNING)", "-" * 30])
        for dup in duplicate_functions:
            schema = dup.get("schema", "")
            name = dup.get("name", "")
            count = dup.get("overload_count", "?")
            lines.append(f"  {schema}.{name} ({count} overloads)")

    if all_warnings:
        lines.extend(["", "WARNINGS", "-" * 30])
        for warning in all_warnings:
            lines.append(f"  {warning}")

    if manifest.has_hard_fail:
        lines.extend(["", "HARD FAILS — DEPLOYMENT IS BLOCKED", "-" * 30])
        for reason in manifest.fail_reasons:
            lines.append(f"  {reason}")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Count verification
# ---------------------------------------------------------------------------
#
# Count verification is the guardrail against silent omissions. The release
# script deploys non-commented deploy.lst entries, so that count must match the
# non-deleted, non-duplicate manifest scope.

def verify_count(manifest: Manifest, deploy_lst_content: str) -> list[str]:
    """Verify the deploy.lst active line count matches the manifest.

    Returns a list of fail reasons (empty if counts match).
    Active deploy.lst lines are non-comment, non-empty lines.
    The manifest count is non-deleted, non-duplicate files.
    """
    deploy_lines = [
        line
        for line in deploy_lst_content.splitlines()
        if line.strip() and not line.startswith("#")
    ]
    deploy_count = len(deploy_lines)

    manifest_files = [
        f
        for f in manifest.sql_files
        if not f.is_deleted and not f.is_duplicate
    ]
    manifest_count = len(manifest_files)

    if deploy_count == manifest_count:
        log.info(
            "Count verification passed: %d file(s) in deploy.lst and manifest.",
            deploy_count,
        )
        return []

    manifest_paths = {f.relative_path for f in manifest_files}
    deploy_paths = set(deploy_lines)

    in_manifest_not_deploy = sorted(manifest_paths - deploy_paths)
    in_deploy_not_manifest = sorted(deploy_paths - manifest_paths)

    fail_msg_parts = [
        f"Count mismatch: deploy.lst has {deploy_count} active entries, "
        f"manifest has {manifest_count} non-deleted non-duplicate files."
    ]
    if in_manifest_not_deploy:
        missing = ", ".join(in_manifest_not_deploy)
        fail_msg_parts.append(f"In manifest but not in deploy.lst: {missing}")
    if in_deploy_not_manifest:
        extra = ", ".join(in_deploy_not_manifest)
        fail_msg_parts.append(f"In deploy.lst but not in manifest: {extra}")

    return fail_msg_parts


# ---------------------------------------------------------------------------
# Artefact checksum manifest
# ---------------------------------------------------------------------------
#
# Checksums make generated artefacts auditable after the release has moved
# through gate approvals and deployment stages.

def _sha256_file(path: str) -> str:
    """Return the hex SHA256 digest of a file."""
    digest = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(65536), b""):
            digest.update(chunk)
    return digest.hexdigest()


def compute_artefact_manifest(release_dir: str, filenames: list[str]) -> dict:
    """Return a dict recording the filename, size in bytes, and SHA256 of each artefact."""
    entries = []
    for filename in filenames:
        path = os.path.join(release_dir, filename)
        if not os.path.exists(path):
            log.warning("Artefact not found for checksum: %s", path)
            continue
        size = os.path.getsize(path)
        checksum = _sha256_file(path)
        entries.append({"filename": filename, "size_bytes": size, "sha256": checksum})
        log.debug("Artefact: %s  sha256=%s  bytes=%d", filename, checksum, size)
    return {"artefacts": entries}


# ---------------------------------------------------------------------------
# Stage runner
# ---------------------------------------------------------------------------
#
# Stage 4 is the first stage that writes the acme release payload. It
# generates every artefact, verifies deploy count consistency, and records
# checksums for Gate 3.

_ARTEFACT_FILENAMES = [
    "prep.sql",
    "deploy.lst",
    "post.sql",
    "delete",
    "NOTES.txt",
]


def run(
    manifest: Manifest,
    static_report: dict,
    db_report: dict,
    cfg: Config,
) -> tuple[Manifest, dict]:
    """Run Stage 4 artefact generation.

    Generates all five release artefacts, runs count verification, writes all
    files to the release directory, and computes the artefact manifest.
    Returns the updated manifest and the artefact manifest dict.
    """
    all_fails: list[str] = []

    drop_order: list[dict] = db_report.get("drop_order", [])
    audit_gaps_raw: list[dict] = db_report.get("audit_gaps", [])

    # Generate file contents.
    prep_sql = generate_prep_sql(manifest, drop_order)
    deploy_lst = generate_deploy_lst(manifest)
    post_sql = generate_post_sql(manifest, audit_gaps_raw)
    delete_content = generate_delete_file(manifest)
    notes_txt = generate_notes_txt(manifest, db_report, cfg.jira_base_url)

    # Count verification.
    count_fails = verify_count(manifest, deploy_lst)
    if count_fails:
        all_fails.extend(count_fails)
        for fail in count_fails:
            log.error("HARD FAIL: %s", fail)

    # Write artefacts.
    release_dir = manifest.release_dir or os.path.join(
        cfg.releases_base_dir, manifest.jira_ticket or "unknown"
    )
    os.makedirs(release_dir, exist_ok=True)

    file_contents = {
        "prep.sql": prep_sql,
        "deploy.lst": deploy_lst,
        "post.sql": post_sql,
        "delete": delete_content,
        "NOTES.txt": notes_txt,
    }

    try:
        for filename, content in file_contents.items():
            path = os.path.join(release_dir, filename)
            with open(path, "w", encoding="utf-8") as fh:
                fh.write(content)
            log.info("Written: %s", path)
    except OSError as exc:
        log.error("Failed to write artefact: %s", exc)
        all_fails.append(f"Artefact write failed: {exc}")

    # Compute and write artefact manifest with SHA256 checksums.
    reports_dir = manifest.reports_dir or os.path.join(release_dir, "reports")
    os.makedirs(reports_dir, exist_ok=True)
    artefact_manifest = compute_artefact_manifest(release_dir, _ARTEFACT_FILENAMES)
    manifest_path = os.path.join(reports_dir, "artefact-manifest.json")
    try:
        with open(manifest_path, "w", encoding="utf-8") as fh:
            json.dump(artefact_manifest, fh, indent=2)
        log.info("Written: %s", manifest_path)
    except OSError as exc:
        log.error("Failed to write artefact manifest: %s", exc)
        all_fails.append(f"Artefact manifest write failed: {exc}")

    if all_fails:
        manifest.has_hard_fail = True
        manifest.fail_reasons.extend(all_fails)

    return manifest, artefact_manifest


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------
#
# The CLI loads all previous stage outputs, writes generated artefacts, updates
# the manifest with any generation failures, and exits non-zero on hard fail.

def main() -> None:
    """CLI entry point for Stage 4 artefact generation."""
    parser = argparse.ArgumentParser(
        description="Stage 4: Artefact generation."
    )
    parser.add_argument("manifest_path", help="Path to raw-manifest.json.")
    parser.add_argument("static_report_path", help="Path to static-analysis-report.json.")
    parser.add_argument("db_report_path", help="Path to db-analysis-report.json.")
    parser.add_argument("--verbose", action="store_true", help="Enable DEBUG logging.")
    args = parser.parse_args()

    configure_logging(verbose=args.verbose)

    try:
        cfg = Config()
    except ConfigError as exc:
        log.error("Configuration error: %s", exc)
        sys.exit(1)

    try:
        with open(args.manifest_path, "r", encoding="utf-8") as fh:
            manifest = Manifest.from_dict(json.load(fh))
    except (OSError, KeyError, ValueError) as exc:
        log.error("Failed to load manifest: %s", exc)
        sys.exit(1)

    if not manifest.sql_changes:
        log.info("Passthrough release — no SQL changes. Skipping.")
        sys.exit(0)

    try:
        with open(args.static_report_path, "r", encoding="utf-8") as fh:
            static_report = json.load(fh)
        with open(args.db_report_path, "r", encoding="utf-8") as fh:
            db_report = json.load(fh)
    except (OSError, KeyError, ValueError) as exc:
        log.error("Failed to load input files: %s", exc)
        sys.exit(1)

    manifest, artefact_manifest = run(manifest, static_report, db_report, cfg)

    release_dir = manifest.release_dir or os.path.join(
        cfg.releases_base_dir, manifest.jira_ticket or "unknown"
    )
    reports_dir = manifest.reports_dir or os.path.join(release_dir, "reports")
    manifest_out = os.path.join(reports_dir, "raw-manifest.json")
    try:
        with open(manifest_out, "w", encoding="utf-8") as fh:
            json.dump(manifest.to_dict(), fh, indent=2)
        log.info("Updated manifest written to %s", manifest_out)
    except OSError as exc:
        log.error("Failed to write updated manifest: %s", exc)
        sys.exit(1)

    if manifest.has_hard_fail:
        log.error(
            "Stage 4 completed with %d hard fail(s). Deployment is blocked.",
            len(manifest.fail_reasons),
        )
        sys.exit(1)

    artefact_count = len(artefact_manifest.get("artefacts", []))
    log.info(
        "Stage 4 complete. %d artefact(s) written to %s.",
        artefact_count,
        release_dir,
    )
    sys.exit(0)


if __name__ == "__main__":
    main()
