-- Generated by: acme-db-pipeline
-- Commit: abc123def456
-- Jira: DEV-1042
-- PR: PR-88
-- Timestamp: 2024-01-15T14:30:00Z

SET ROLE "acme_admin";

-- This file is classified as a schema file but incorrectly contains a DROP FUNCTION.
-- DROP statements belong in prep.sql only.
DROP FUNCTION IF EXISTS public.old_helper(uuid);

ALTER TABLE public.orders ADD COLUMN filled_at timestamp;
