-- Generated by: acme-db-pipeline
-- Commit: abc123def456
-- Jira: DEV-1042
-- PR: PR-88
-- Timestamp: 2024-01-15T14:30:00Z

SET ROLE "acme_admin";

CREATE OR REPLACE FUNCTION public.escalation_func(p_id uuid)
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE NOTICE 'doing something';
END;
$$;

GRANT EXECUTE ON FUNCTION public.escalation_func(uuid) TO web_user;
