-- Generated by: acme-db-pipeline
-- Commit: abc123def456
-- Jira: DEV-1042
-- PR: PR-88
-- Timestamp: 2024-01-15T14:30:00Z

SET ROLE "acme_admin";

-- This file is classified as a function file but incorrectly contains DDL.
CREATE TABLE public.should_not_be_here (
    id uuid PRIMARY KEY,
    name text NOT NULL
);

CREATE OR REPLACE FUNCTION public.some_func(p_id uuid)
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE NOTICE 'function body';
END;
$$;
