-- Generated by: acme-db-pipeline
-- Commit: abc123def456
-- Jira: DEV-1042
-- PR: PR-88
-- Timestamp: 2024-01-15T14:30:00Z

SET ROLE "acme_admin";

CREATE OR REPLACE FUNCTION public.deactivate_user(p_user_id uuid)
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
    -- Deleting the user record will CASCADE to child tables via FK constraints.
    UPDATE public.users SET active = false WHERE id = p_user_id;
END;
$$;
