-- Generated by: acme-db-pipeline
-- Commit: abc123def456
-- Jira: DEV-1042
-- PR: PR-88
-- Timestamp: 2024-01-15T14:30:00Z

   set role "acme_admin";

create table public.invoices (
   id        uuid primary key default gen_random_uuid(),
   order_id  uuid not null
      references public.orders ( id ),
   amount    numeric(12,2) not null,
   issued_at timestamp not null default now(),
   paid_at   timestamp
);
