-- Generated by: acme-db-pipeline
-- Commit: abc123def456
-- Jira: DEV-1027
-- PR: PR-1027
-- Timestamp: 2024-01-15T14:30:00Z

SET ROLE "acme_admin";

CREATE OR REPLACE FUNCTION "acme_api"."get_reward_estimate"(
    p_miner_id    UUID,
    p_hours       INTEGER DEFAULT 72,
    p_min_amount  NUMERIC  DEFAULT 0
)
RETURNS NUMERIC
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
AS $$
DECLARE
    v_estimate NUMERIC;
BEGIN
    SELECT COALESCE(
        SUM(amount) / NULLIF(COUNT(DISTINCT DATE_TRUNC('hour', created_at)), 0) * p_hours,
        0
    )
    INTO v_estimate
    FROM "acme_api"."payments"
    WHERE miner_id = p_miner_id
      AND created_at > NOW() - INTERVAL '21 days'
      AND amount >= p_min_amount;

    RETURN v_estimate;
END;
$$;
