-- Generated by: acme-db-pipeline
-- Commit: abc123def456
-- Jira: DEV-1042
-- PR: PR-88
-- Timestamp: 2024-01-15T14:30:00Z

SET ROLE "acme_admin";

CREATE OR REPLACE FUNCTION public.get_user_by_id(p_user_id uuid)
RETURNS TABLE(id uuid, email text, created_at timestamp)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT u.id, u.email, u.created_at
    FROM public.users u
    WHERE u.id = p_user_id;
END;
$$;
