-- Generated by: acme-db-pipeline
-- Commit: abc123def456
-- Jira: DEV-1042
-- PR: PR-88
-- Timestamp: 2024-01-15T14:30:00Z

SET ROLE "acme_admin";

CREATE TYPE public.order_status AS ENUM (
    'pending',
    'confirmed',
    'filled',
    'cancelled',
    'expired'
);
